## Multi Stage Build
# Stage 1 Build phase
FROM mcr.microsoft.com/dotnet/core/sdk:2.2.402-bionic AS build
WORKDIR /src
COPY ["CatalogAPI.csproj", "./"]
RUN dotnet restore
COPY . .
RUN dotnet build -c Release -o /bin
RUN dotnet publish -c Release -o /dist

# Stage 2
FROM mcr.microsoft.com/dotnet/core/aspnet:2.2.7-bionic AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

ENV MongoSettings:ConnectionString=mongodb://amol-cosmosmongo-account:PZvBL3MCsXSRcVIKCmfsxVtKhGv9PZHSavOPISizaaESEFxzqmZe9xOqvuwkqRdPjcU0bC2CK0r17f9J6ob0uQ==@amol-cosmosmongo-account.documents.azure.com:10255/?ssl=true&replicaSet=globaldb&retryWrites=false
ENV MongoSettings:Database=CatalogDB
ENV ConnectionStrings:StorageConnection=DefaultEndpointsProtocol=https;AccountName=amolsstorageaccount;AccountKey=mfJz2eB/7q/o/5c14KlRg9JKISF0JX93YtS3fqPRz84KLRgqH9Qjgm90oeiGmYCrC8MLjFdA0+XUxE3IShYSMg==;EndpointSuffix=core.windows.net
ENV ConnectionStrings:TableConnection=DefaultEndpointsProtocol=https;AccountName=amol-cosmos-azuretable-account;AccountKey=FRYXncdHl6aUQKlYKRfBQfo6tvhTRNZRDy8odTxmoNAKMztLobSSCGEPQyElgR2TGeS6MB6U3oInPjjtgsPm7w==;TableEndpoint=https://amol-cosmos-azuretable-account.table.cosmos.azure.com:443/

COPY --from=build /dist .
ENTRYPOINT ["dotnet", "CatalogAPI.dll"]